# Generated by Django 4.2.4 on 2023-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_remove_rental_selected_options_delete_rentaloption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
