# Generated by Django 4.2.4 on 2023-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_userprofile_remove_rental_client_rental_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='average_fuel_consumption',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='boot_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_seats',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
