# Generated by Django 4.2.4 on 2023-08-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_caradmin_alter_car_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarAdmin',
        ),
    ]
