# Generated by Django 4.2.4 on 2023-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_alter_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
