# Generated by Django 4.2.4 on 2023-09-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='ContactMessage',
        ),
    ]
