# Generated by Django 4.2.4 on 2023-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_alter_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
