# Generated by Django 4.2.4 on 2023-09-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_rename_email_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=False, max_length=200, null=True),
        ),
    ]
