# Generated by Django 4.2.4 on 2023-09-02 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
