# Generated by Django 4.2.4 on 2023-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0007_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=True, max_length=1000, null=True),
        ),
    ]
